[workspace]
resolver = "3"
members = ["wasodecs"]

[workspace.package]
version = "0.3.11"
edition = "2024"
authors = ["mlm-games"] # Old: ["Luke Curley"]
repository = "https://github.com/mlm-games/web-rs"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
bytemuck = "1.25"
bytes = "1.11"
derive_more = { version = "2.1", features = ["from", "display"] }
js-sys = "0.3"
thiserror = "2.0"
tokio = "1.52"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3.102"
web-workers = { version = "0.3", features = ["message"] }
