[workspace]
resolver = "3"
members = ["web-async", "web-codecs", "web-message", "web-message-derive", "web-streams"]

[workspace.package]
edition = "2024"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/web-rs"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
bytemuck = "1.25"
bytes = "1.11"
derive_more = { version = "2.1", features = ["from", "display"] }
js-sys = "0.3"
proc-macro2 = "1"
quote = "1.0"
syn = { version = "2.0.117", features = ["full"] }
thiserror = "2.0"
tokio = "1.52"
tracing = "0.1"
url = "2.5.8"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3.99"

web-message-derive = { path = "web-message-derive" }
