[package]
name = "web-message-derive"
description = "A macro that converts Rust structs to/from JavaScript objects via postMessage."
version = "0.0.2"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

categories = ["wasm", "web-programming"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
