[package]
name = "web-async"
description = "Async helpers and utilities for WASM"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/web-rs"
license = "MIT OR Apache-2.0"

version = "0.1.3"
edition = "2021"

keywords = ["wasm", "async", "futures"]
categories = ["wasm"]

[features]
tracing = ["dep:tracing"]

[dependencies]
tracing = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { workspace = true }
