[package]
name = "web-streams"
description = "WASM bindings for the Streams API"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/web-rs"
license = "MIT OR Apache-2.0"

version = "0.1.4"
edition = "2021"

categories = ["wasm", "web-programming", "api-bindings"]

[dependencies]
thiserror = "2.0.18"
wasm-bindgen = "0.2.122"
wasm-bindgen-futures = "0.4.72"
tokio = { version = "1.52.3", features = ["io-util"], optional = true }
tracing = { version = "0.1.44", optional = true}


[features]
tokio = ["dep:tokio", "dep:tracing"]

[dependencies.web-sys]
version = "0.3.99"
features = [
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "ReadableStreamReadResult",
    "WritableStream",
    "WritableStreamDefaultWriter",
]
