[package]
name = "web-codecs"
description = "WASM bindings for Web Codecs"
version = "0.3.10"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

categories = ["wasm", "multimedia", "web-programming", "api-bindings"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "web_sys_unstable_apis"]
rustc-args = ["--cfg", "web_sys_unstable_apis"]

[dependencies]
bytemuck = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
js-sys = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    "VideoDecoder",
    "VideoDecoderInit",
    "VideoDecoderConfig",
    "VideoDecoderSupport",
    "VideoFrame",
    "VideoColorSpace",
    "VideoColorSpaceInit",
    "EncodedVideoChunk",
    "EncodedVideoChunkInit",
    "EncodedVideoChunkType",
    "HardwareAcceleration",
    "VideoMatrixCoefficients",
    "VideoColorPrimaries",
    "VideoTransferCharacteristics",
    "VideoEncoder",
    "VideoEncoderInit",
    "VideoEncoderConfig",
    "VideoEncoderEncodeOptions",
    "VideoEncoderSupport",
    "LatencyMode",
    "AlphaOption",
    "EncodedAudioChunk",
    "EncodedAudioChunkInit",
    "EncodedAudioChunkType",
    "AudioData",
    "AudioDecoder",
    "AudioDecoderInit",
    "AudioDecoderConfig",
    "AudioDecoderSupport",
    "AudioEncoder",
    "AudioEncoderInit",
    "AudioEncoderConfig",
    "AudioEncoderSupport",
    "AudioSampleFormat",
    "AudioDataCopyToOptions",
    "AudioDataInit",
    "console",
    "PlaneLayout",
]
