name: Release crates
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create GitHub Release"
        required: true
        default: true
        type: boolean
      bump_type:
        description: "Version bump type (none/patch/minor/major)"
        required: false
        default: "patch"
        type: choice
        options:
          - none
          - patch
          - minor
          - major

jobs:
  release:
    permissions:
      contents: write
    uses: mlm-games/ci/.github/workflows/crate-publish.yml@main
    with:
      bump-type: ${{ inputs.bump_type }}
      create-release: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.create_release) }}
      workspace-publish: true
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}